importScripts('./site-map.js?v=20260829-2');

const VERSION = 'basc-v2.5.0-basi-cachefix';
const SHELL = ['./','./index.html','./styles.css?v=20260829-2','./content-pages.css?v=20260829-2','./banner.css?v=20260829-2','./candidate-hero.css?v=20260829-2','./ui-fixes.css?v=20260829-2','./app.js?v=20260829-2','./config.js?v=20260829-2','./bot-config.js?v=20260829-2','./site-map.js?v=20260829-2','./banner.js?v=20260829-2','./search.js?v=20260829-2','./site-bot-v2.js?v=20260829-2','./footer.js?v=20260829-2','./404.html'];

self.addEventListener('install',event=>event.waitUntil(caches.open(VERSION).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==VERSION).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
function pathOf(url){return new URL(url).pathname.replace(/\/+$/,'')||'/';}
function sameOrigin(url){return new URL(url).origin===self.location.origin;}
function isKnownPath(path){const map=self.BASC_SITE_MAP||{};const aliases=map.aliases||{};const canonical=aliases[path]||path;return path===map.home||Object.keys(map).some(k=>k!=='aliases'&&map[k]===path)||Object.values(aliases).includes(path)||canonical===map.home||Object.keys(map).some(k=>k!=='aliases'&&map[k]===canonical);}
async function navigationResponse(url){const known=isKnownPath(pathOf(url));const shell=known?'./index.html':'./404.html';try{const response=await fetch(`${shell}?v=${VERSION}`,{cache:'no-store'});if(!response.ok)throw new Error('navigation failed');const body=await response.blob();const headers=new Headers(response.headers);caches.open(VERSION).then(cache=>cache.put(shell,new Response(body,{headers}))).catch(()=>{});return new Response(body,{status:known?200:404,statusText:known?'OK':'Not Found',headers});}catch{const fallback=await caches.match(shell);if(!fallback)return Response.error();const body=await fallback.blob();return new Response(body,{status:known?200:404,statusText:known?'OK':'Not Found',headers:fallback.headers});}}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET'||!sameOrigin(request.url))return;if(request.mode==='navigate'){event.respondWith(navigationResponse(request.url));return;}event.respondWith((async()=>{try{const fresh=await fetch(request,{cache:'no-store'});if(fresh.ok){const copy=fresh.clone();caches.open(VERSION).then(cache=>cache.put(request,copy)).catch(()=>{});}return fresh;}catch{return(await caches.match(request))||Response.error();}})());});
