(() => {
  'use strict';
  const POLL_MS = 15000;
  const CONFIG_URL = '../config.js';
  const BANNER_ID = 'liveBanner';
  let activeSignature = '';
  let latestBanner = null;
  let requestInFlight = false;
  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function signature(v){try{return JSON.stringify(v||null)}catch{return ''}}
  function getBanner(config){const banner=config?.banner;if(!banner||banner.enabled===false)return null;return banner}
  function root(){let el=document.getElementById(BANNER_ID);if(!el){el=document.createElement('section');el.id=BANNER_ID;el.className='live-banner-host';el.hidden=true;const h=document.querySelector('.site-header');document.body.insertBefore(el,h||document.body.firstChild)}return el}
  function link(a){const style=a.style==='secondary'?' secondary':a.style==='ghost'?' ghost':'';return `<a class="live-banner-action${style}" href="${esc(a.href||'#')}"${a.target==='_blank'?' target="_blank" rel="noopener noreferrer"':''}>${esc(a.label||'Open')}</a>`}
  function content(blocks){if(!Array.isArray(blocks))return '';return blocks.map(b=>{if(!b||typeof b!=='object')return '';if(b.type==='link')return `<a class="live-banner-inline-link" href="${esc(b.href||'#')}"${b.target==='_blank'?' target="_blank" rel="noopener noreferrer"':''}>${esc(b.label||b.href)}</a>`;if(b.type==='badge')return `<span class="live-banner-badge">${esc(b.text||'')}</span>`;if(b.type==='heading')return `<h3>${esc(b.text||'')}</h3>`;return `<p>${esc(b.text||'')}</p>`}).join('')}
  function render(banner){const el=root();latestBanner=banner||null;activeSignature=signature(banner);if(!banner){el.hidden=true;el.innerHTML='';document.documentElement.classList.remove('has-live-banner');return}const expandable=banner.expandable&&banner.expandable.enabled!==false;const actions=Array.isArray(banner.actions)?banner.actions.filter(a=>a&&a.href&&a.label):[];el.innerHTML=`<div class="live-banner tone-${esc(banner.tone||'default')}" role="region" aria-label="Site announcement"><div class="live-banner-inner"><div class="live-banner-copy">${banner.eyebrow?`<span class="live-banner-eyebrow">${esc(banner.eyebrow)}</span>`:''}<div class="live-banner-message"><strong>${esc(banner.title||'')}</strong>${banner.message?`<span>${esc(banner.message)}</span>`:''}${content(banner.content)}</div></div><div class="live-banner-actions">${actions.map(link).join('')}${expandable?`<button class="live-banner-expand" type="button" data-banner-expand>${esc(banner.expandable.label||'Learn more')} ↗</button>`:''}${banner.dismissible===false?'':'<button class="live-banner-close" type="button" aria-label="Dismiss">×</button>'}</div></div></div>`;el.hidden=false;document.documentElement.classList.add('has-live-banner');el.querySelector('.live-banner-close')?.addEventListener('click',()=>{el.hidden=true;document.documentElement.classList.remove('has-live-banner')});el.querySelector('[data-banner-expand]')?.addEventListener('click',()=>openDetail())}
  function openDetail(){const data=latestBanner?.expandable;if(!data)return;let modal=document.getElementById('liveBannerOverlay');if(!modal){modal=document.createElement('div');modal.id='liveBannerOverlay';modal.className='live-banner-overlay';document.body.appendChild(modal)}modal.hidden=false;modal.innerHTML=`<div class="live-banner-backdrop" data-close></div><div class="live-banner-dialog" role="dialog" aria-modal="true"><div class="live-banner-dialog-top"><span>${esc(data.eyebrow||latestBanner.eyebrow||'Announcement')}</span><button type="button" data-close aria-label="Close">×</button></div><div class="live-banner-dialog-body"><h2>${esc(data.title||latestBanner.title||'')}</h2>${data.body?`<p>${esc(data.body)}</p>`:''}${(data.sections||[]).map(s=>`<section><h3>${esc(s.title||'')}</h3><p>${esc(s.body||'')}</p></section>`).join('')}</div></div>`;modal.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',()=>{modal.hidden=true}))}
  async function poll(){if(requestInFlight)return;requestInFlight=true;try{const response=await fetch(`${CONFIG_URL}?live=${Date.now()}`,{cache:'no-store',credentials:'same-origin'});if(!response.ok)return;const source=await response.text();const sandbox={};const config=new Function('window',`${source}\n;return window.SITE_CONFIG`)(sandbox);const banner=getBanner(config);if(signature(banner)!==activeSignature)render(banner)}catch{}finally{requestInFlight=false}}
  function start(){render(getBanner(window.SITE_CONFIG));poll();setInterval(poll,POLL_MS)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
